</div>
<div id="globalToastContainer"></div>
<style>
#globalToastContainer{position:fixed;right:24px;bottom:24px;z-index:99999;pointer-events:none}.global-toast{min-width:320px;margin-top:12px;padding:15px 18px;border-radius:18px;background:linear-gradient(135deg,#7c3cff,#10dff0);color:#fff;font-size:13px;font-weight:800;box-shadow:0 0 28px rgba(124,60,255,.28);animation:toastIn .25s ease;pointer-events:auto}@keyframes toastIn{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)}}@media(max-width:768px){#globalToastContainer{left:14px;right:14px;bottom:14px}.global-toast{min-width:auto;width:100%}}
</style>
<script>
const baseUrlDashboard='<?= base_url() ?>';
function formatNumber(num){if(num===undefined||num===null)return'0';const n=parseFloat(num);return isNaN(n)?'0':n.toLocaleString('id-ID',{minimumFractionDigits:0,maximumFractionDigits:0});}
function escapeHtml(str){if(!str)return'';return String(str).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
function showToastGlobal(message,type='success'){const c=document.getElementById('globalToastContainer');if(!c)return;const t=document.createElement('div');t.className='global-toast';t.innerHTML=`<i class="fas fa-${type==='success'?'check-circle':'exclamation-circle'}"></i> ${message}`;c.appendChild(t);setTimeout(()=>t.remove(),3000);}
function showChangePasswordModal(){document.getElementById('changePasswordModal')?.classList.add('show');}
function closeChangePasswordModal(){document.getElementById('changePasswordModal')?.classList.remove('show');['currentPassword','newPassword','confirmPassword'].forEach(id=>{const el=document.getElementById(id);if(el)el.value='';});}
let currentUserRole='<?= $this->session->userdata('role') ?>';
function showAddUserModal(){const l=document.getElementById('addUserRoleLabel');if(l)l.innerText=currentUserRole?'('+currentUserRole+')':'';document.getElementById('addUserModal')?.classList.add('show');}
function closeAddUserModal(){document.getElementById('addUserModal')?.classList.remove('show');['newUsername','newUserPassword','newUserFullname','newUserEmail'].forEach(id=>{const el=document.getElementById(id);if(el)el.value='';});}
async function showActivityLogModal(){const modal=document.getElementById('activityLogModal'),content=document.getElementById('activityLogContent');modal?.classList.add('show');if(!content)return;content.innerHTML='<div class="loading">Loading logs...</div>';try{const r=await fetch(baseUrlDashboard+'auth/get_user_logs');const d=await r.json();if(d.success&&d.logs&&d.logs.length){content.innerHTML=d.logs.map(log=>`<div class="log-item"><div class="log-time">${escapeHtml(log.created_at)}</div><div class="log-action">${escapeHtml(log.action)}</div><div class="log-description">${escapeHtml(log.description||'-')}</div><div class="log-time">IP: ${escapeHtml(log.ip_address||'-')}</div></div>`).join('');}else content.innerHTML='<div class="empty-state">Belum ada aktivitas</div>';}catch(e){content.innerHTML='<div class="empty-state">Gagal memuat aktivitas</div>';}}
function closeActivityLogModal(){document.getElementById('activityLogModal')?.classList.remove('show');}
document.getElementById('savePasswordBtn')?.addEventListener('click',async()=>{const current_password=document.getElementById('currentPassword').value,new_password=document.getElementById('newPassword').value,confirm_password=document.getElementById('confirmPassword').value;if(!current_password||!new_password||!confirm_password)return showToastGlobal('Semua field harus diisi','error');if(new_password!==confirm_password)return showToastGlobal('Password baru tidak sama','error');if(new_password.length<6)return showToastGlobal('Password minimal 6 karakter','error');try{const r=await fetch(baseUrlDashboard+'auth/change_password',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({current_password,new_password,confirm_password})});const d=await r.json();if(d.success){showToastGlobal('Password berhasil diubah');closeChangePasswordModal();}else showToastGlobal(d.message||'Gagal mengubah password','error');}catch(e){showToastGlobal('Gagal mengubah password','error');}});
document.getElementById('saveUserBtn')?.addEventListener('click',async()=>{const username=document.getElementById('newUsername').value,password=document.getElementById('newUserPassword').value,full_name=document.getElementById('newUserFullname').value,email=document.getElementById('newUserEmail').value;if(!username||!password)return showToastGlobal('Username dan password harus diisi','error');if(password.length<6)return showToastGlobal('Password minimal 6 karakter','error');try{const r=await fetch(baseUrlDashboard+'auth/add_user',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({username,password,full_name,email,role:currentUserRole})});const d=await r.json();if(d.success){showToastGlobal(d.message||'User berhasil dibuat');closeAddUserModal();setTimeout(()=>location.reload(),1200);}else showToastGlobal(d.message||'Gagal membuat user','error');}catch(e){showToastGlobal('Gagal membuat user','error');}});
window.addEventListener('click',e=>{['changePasswordModal','addUserModal','activityLogModal','campaignModal'].forEach(id=>{const m=document.getElementById(id);if(e.target===m)m.classList.remove('show');});});
</script>
</body>
</html>
